# Generated by Django 4.2.11 on 2025-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=4.5)),
                ('description', models.TextField(blank=True, default='')),
                ('is_best_seller', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='cakes/')),
            ],
        ),
    ]
