# Generated by Django 4.2.11 on 2025-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(upload_to='dessert/'),
        ),
    ]
