# Generated by Django 4.2.11 on 2025-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='beverages/')),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=4.5)),
                ('is_best_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
