# Generated by Django 4.2.11 on 2025-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(default=4.5)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='gifts/')),
            ],
        ),
    ]
