# Generated by Django 4.2.11 on 2025-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
